CREATE DATABASE IF NOT EXISTS livox;

USE livox;

CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(20) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone INT NOT NULL
    );
    